
package vistas;

import AceesoDatos.MesaData;
import AceesoDatos.PedidoData;
import AceesoDatos.PedidoProductoData;
import AceesoDatos.ProductoData;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Mesa;
import modelo.Pedido;
import modelo.PedidoProducto;
import modelo.Producto;


public class Sistema extends javax.swing.JFrame {
private DefaultTableModel modelo = new DefaultTableModel();
    Producto pro = new Producto();
    ProductoData prodata = new ProductoData();
    Mesa mesa = new Mesa();
    MesaData medata = new MesaData();
    Pedido pedido = new Pedido();
    PedidoData pedata = new PedidoData();
    PedidoProductoData pedro = new PedidoProductoData();
    PedidoProducto pedipro = new PedidoProducto();
    private Producto productoActual = null;
    double precio=0;
    int cantidad=0;
    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
        this.setLocationRelativeTo(null);
        
       
        armarCabeceraPedidos();
        llenarComboPED();
       llenarComboPedido();
       llenarComboProducto();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbotonProducto = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jbotonMesas = new javax.swing.JButton();
        jbotonPedido = new javax.swing.JButton();
        jbPedidoProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtIdVent = new javax.swing.JTextField();
        jtCantidadVent = new javax.swing.JTextField();
        jcbProductosVen = new javax.swing.JComboBox<>();
        jcbPedidoVen = new javax.swing.JComboBox<>();
        jlSubtotal = new javax.swing.JLabel();
        jbEjecutar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jbTotal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jtIdPedido = new javax.swing.JTextField();
        jtImporte = new javax.swing.JTextField();
        jrbCobro = new javax.swing.JRadioButton();
        jbAgregarPedido = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jcbIdMesaPed = new javax.swing.JComboBox();
        jtNombreMesero = new javax.swing.JTextField();
        jtIdMesaPedido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaPedidos = new javax.swing.JTable();
        jbEliminarPedido = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtNumeroMesa = new javax.swing.JTextField();
        jtCapacidadMesa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtIdMesa = new javax.swing.JTextField();
        jrbEstadoMesa = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtTablaMesa = new javax.swing.JTable();
        jbAgregarMesa = new javax.swing.JButton();
        jbLimpiarMesa = new javax.swing.JButton();
        jbEliminarMesa = new javax.swing.JButton();
        jbModificarMesa = new javax.swing.JButton();
        jbBuscarMesa = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtID = new javax.swing.JTextField();
        jtNombreBuscar = new javax.swing.JTextField();
        jtPrecio = new javax.swing.JTextField();
        jtCantidad = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProducto = new javax.swing.JTable();
        jbModificarP = new javax.swing.JButton();
        jbAgregarP = new javax.swing.JButton();
        jbEliminarP = new javax.swing.JButton();
        jbConsultarP = new javax.swing.JButton();
        jrbEstado = new javax.swing.JRadioButton();
        jbLimpiarP = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        jbotonProducto.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbotonProducto.setText("Productos");
        jbotonProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotonProductoActionPerformed(evt);
            }
        });

        jButton2.setText("jButton1");

        jButton3.setText("jButton1");

        jButton4.setText("jButton1");

        jbotonMesas.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbotonMesas.setText("Mesas");
        jbotonMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotonMesasActionPerformed(evt);
            }
        });

        jbotonPedido.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbotonPedido.setText("Pedido");
        jbotonPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotonPedidoActionPerformed(evt);
            }
        });

        jbPedidoProducto.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbPedidoProducto.setText("Realizar Venta");
        jbPedidoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPedidoProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jbotonMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbPedidoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(jbotonProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbotonPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jbPedidoProducto)
                .addGap(18, 18, 18)
                .addComponent(jbotonPedido)
                .addGap(18, 18, 18)
                .addComponent(jbotonMesas)
                .addGap(18, 18, 18)
                .addComponent(jbotonProducto)
                .addGap(435, 435, 435)
                .addComponent(jButton2)
                .addGap(226, 226, 226)
                .addComponent(jButton4)
                .addGap(226, 226, 226)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 660));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rafa\\Pictures\\menu.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 500, 190));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\rafa\\Pictures\\menu.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 500, 190));

        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel2.setText("id");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel4.setText("Pedido");

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel6.setText("Producto");

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel7.setText("Cantidad");

        jcbPedidoVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPedidoVenActionPerformed(evt);
            }
        });

        jlSubtotal.setIcon(new javax.swing.ImageIcon("C:\\Users\\rafa\\Downloads\\mano.png")); // NOI18N

        jbEjecutar.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbEjecutar.setText("Enter");
        jbEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEjecutarActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel17.setText("Total pagar");

        jlTotal.setIcon(new javax.swing.ImageIcon("C:\\Users\\rafa\\Downloads\\mano.png")); // NOI18N

        jLabel21.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel21.setText("Subtotal");

        jbTotal.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbTotal.setText("Final");
        jbTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtIdVent, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jcbPedidoVen, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(127, 127, 127)
                        .addComponent(jLabel7)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jcbProductosVen, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtCantidadVent, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(779, 779, 779)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlSubtotal)
                        .addGap(99, 99, 99)
                        .addComponent(jlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jbEjecutar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jbTotal)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtIdVent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbProductosVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbPedidoVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCantidadVent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jbEjecutar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSubtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21))
                .addGap(31, 31, 31))
        );

        jTabbedPane2.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel14.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel14.setText("id");

        jLabel18.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel18.setText("Nombre mesero");

        jLabel19.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel19.setText("Importe");

        jLabel20.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel20.setText("Cobro");

        jtIdPedido.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        jtImporte.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        jbAgregarPedido.setText("Agregar");
        jbAgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarPedidoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel5.setText("Id Mesa");

        jcbIdMesaPed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Listado de mesas" }));

        jtTablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtTablaPedidos);

        jbEliminarPedido.setText("Eliminar");
        jbEliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarPedidoActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addGap(67, 67, 67))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jcbIdMesaPed, 0, 241, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtIdMesaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtNombreMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrbCobro, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(54, 54, 54)
                        .addComponent(jbAgregarPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbEliminarPedido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel5)
                    .addComponent(jLabel18))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbIdMesaPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtNombreMesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtIdMesaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jrbCobro)
                            .addComponent(jtImporte)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbAgregarPedido)
                            .addComponent(jbEliminarPedido)
                            .addComponent(jButton1))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab2", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel13.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel13.setText("Numero de Mesa");

        jLabel15.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel15.setText("Capacidad");

        jLabel16.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel16.setText("Id");

        jrbEstadoMesa.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jrbEstadoMesa.setText("Estado");

        jtTablaMesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtTablaMesa);

        jbAgregarMesa.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbAgregarMesa.setText("Agregar");
        jbAgregarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarMesaActionPerformed(evt);
            }
        });

        jbLimpiarMesa.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbLimpiarMesa.setText("Limpiar");
        jbLimpiarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarMesaActionPerformed(evt);
            }
        });

        jbEliminarMesa.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbEliminarMesa.setText("Eliminar");
        jbEliminarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarMesaActionPerformed(evt);
            }
        });

        jbModificarMesa.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbModificarMesa.setText("Modificar");
        jbModificarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarMesaActionPerformed(evt);
            }
        });

        jbBuscarMesa.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbBuscarMesa.setIcon(new javax.swing.ImageIcon("C:\\Users\\rafa\\Downloads\\Lupa para netbeans.jpg")); // NOI18N
        jbBuscarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jtCapacidadMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15))
                            .addComponent(jrbEstadoMesa)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jtNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jtIdMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbBuscarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(jbLimpiarMesa)))
                                .addGap(20, 20, 20)
                                .addComponent(jbModificarMesa))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jbAgregarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbEliminarMesa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbBuscarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtIdMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbLimpiarMesa)
                                .addComponent(jbModificarMesa)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtCapacidadMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addComponent(jrbEstadoMesa)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbAgregarMesa)
                            .addComponent(jbEliminarMesa))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("tab3", jPanel4);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel8.setText("id");

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel9.setText("Nombre");

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel10.setText("Precio");

        jLabel11.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel11.setText("Cantidad");

        jLabel12.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel12.setText("Estado");

        jtNombreBuscar.setToolTipText("");
        jtNombreBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtNombreBuscarKeyReleased(evt);
            }
        });

        jTableProducto.setBackground(new java.awt.Color(204, 204, 255));
        jTableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableProducto);

        jbModificarP.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbModificarP.setText("Modificar");
        jbModificarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarPActionPerformed(evt);
            }
        });

        jbAgregarP.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbAgregarP.setText("Agregar");
        jbAgregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarPActionPerformed(evt);
            }
        });

        jbEliminarP.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbEliminarP.setText("Eliminar");
        jbEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarPActionPerformed(evt);
            }
        });

        jbConsultarP.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbConsultarP.setText("Consultar");
        jbConsultarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarPActionPerformed(evt);
            }
        });

        jrbEstado.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jrbEstado.setText("Estado");

        jbLimpiarP.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jbLimpiarP.setText("Limpiar");
        jbLimpiarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarPActionPerformed(evt);
            }
        });

        jbActualizar.setText("Atualizar");
        jbActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbActualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jbConsultarP)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(63, 63, 63))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jtID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(55, 55, 55)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jrbEstado)
                                .addGap(42, 42, 42)
                                .addComponent(jbAgregarP)
                                .addGap(18, 18, 18)
                                .addComponent(jbLimpiarP))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel12)))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jbActualizar)
                        .addGap(77, 77, 77)
                        .addComponent(jbModificarP)
                        .addGap(85, 85, 85)
                        .addComponent(jbEliminarP)
                        .addContainerGap())))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbEstado)
                    .addComponent(jbConsultarP)
                    .addComponent(jbAgregarP)
                    .addComponent(jbLimpiarP))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbActualizar)
                    .addComponent(jbModificarP)
                    .addComponent(jbEliminarP))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab4", jPanel5);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 1000, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbotonProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotonProductoActionPerformed
            
        llenarTablaProducto();
       jTabbedPane2.setSelectedIndex(3);
        
    }//GEN-LAST:event_jbotonProductoActionPerformed

    private void jbotonMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotonMesasActionPerformed
       
        llenarTablaMesa();
        jTabbedPane2.setSelectedIndex(2);
       
    }//GEN-LAST:event_jbotonMesasActionPerformed

    private void jbotonPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotonPedidoActionPerformed
        llenarTablaPedido();
        jTabbedPane2.setSelectedIndex(1);
        
    }//GEN-LAST:event_jbotonPedidoActionPerformed

    private void jbModificarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarPActionPerformed
      //    Modificar funciona solamente si consulto el nombre
      
      if("".equals(jtID.getText())){
          JOptionPane.showMessageDialog(this, "Seleccione una fila ");
             }else{
               productoActual.setNombreProducto(jtNombreBuscar.getText());
               productoActual.setPrecio(Double.parseDouble(jtPrecio.getText()));
               productoActual.setStock(Integer.parseInt(jtCantidad.getText()));
               productoActual.setEstado(jrbEstado.isSelected());
               prodata.modificarProducto(productoActual);
      } 

    }//GEN-LAST:event_jbModificarPActionPerformed

    private void jbAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarPActionPerformed
     
       try{
       
        String nombre = jtNombreBuscar.getText();
        Double precio = Double.parseDouble(jtPrecio.getText());
        Integer cantidad = Integer.parseInt(jtCantidad.getText());
        Boolean estado = jrbEstado.isSelected();
        
        productoActual = new Producto( nombre, precio, cantidad, estado);
        prodata.agregarproducto( productoActual);
           
       }catch(NumberFormatException ex){
     JOptionPane.showMessageDialog(this, "Debe ingresar ");
    }
      llenarTablaProducto();
        
    }//GEN-LAST:event_jbAgregarPActionPerformed

    private void jbEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarPActionPerformed
        int filasSelec=jTableProducto.getSelectedRow();
        if(filasSelec != -1){
            int idM = (Integer)modelo.getValueAt(filasSelec, 0);
            prodata.eliminarProducto(idM);
//            indata.borrarInscripcionMateriaAlumno(alumnoSeleccionado.getIdAlumno(), idM);
            
        }else{
           JOptionPane.showMessageDialog(this, "Por favor seleccione un producto");
        }
      llenarTablaProducto();
    }//GEN-LAST:event_jbEliminarPActionPerformed

    private void jbConsultarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarPActionPerformed
         try{
//              Integer id = Integer.parseInt(jtID.getText());
//              productoActual = prodata.buscarProducto(id);
            String nombre = jtNombreBuscar.getText();
            productoActual = prodata.consultarProducto(nombre);
            if(productoActual !=null){
             
              jtID.setText(""+productoActual.getIdProducto());
              jtNombreBuscar.setText(productoActual.getNombreProducto());
              jtPrecio.setText(""+productoActual.getPrecio());
              jtCantidad.setText(""+productoActual.getStock());
              jrbEstado.setSelected(productoActual.isEstado());
              
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Debe ingresar ");
        }
    }//GEN-LAST:event_jbConsultarPActionPerformed

    private void jbLimpiarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarPActionPerformed
        limpiarProducto();
        productoActual=null;
        llenarTablaProducto();
    }//GEN-LAST:event_jbLimpiarPActionPerformed

    private void jbPedidoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPedidoProductoActionPerformed
      
        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_jbPedidoProductoActionPerformed

    private void jtNombreBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNombreBuscarKeyReleased
         borrarFilasProducto();
            for(Producto p:prodata.listarProducto()){
                 if(p.getNombreProducto().startsWith(jtNombreBuscar.getText())){
                modelo.addRow(new Object[]{p.getIdProducto(),p.getNombreProducto(),p.getPrecio(),p.getStock(),p.isEstado()});
            }
            }
    }//GEN-LAST:event_jtNombreBuscarKeyReleased

    private void jTableProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductoMouseClicked
         int fsec=jTableProducto.getSelectedRow();
          if(fsec != -1){
             jtID.setText(modelo.getValueAt(fsec, 0).toString());//pongo un integer porque quiero pasarlo de Object a entero
              
             jtNombreBuscar.setText(modelo.getValueAt(fsec, 1).toString());
             jtPrecio.setText(modelo.getValueAt(fsec, 2).toString());
             jtCantidad.setText(modelo.getValueAt(fsec, 3).toString()); 
//             jrbEstado.setSelected(Boolean.parseBoolean((String) modelo.getValueAt(fsec, 4)));
             }
               
    }//GEN-LAST:event_jTableProductoMouseClicked

    private void jbAgregarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarMesaActionPerformed
         try{
        Integer numeroMesa = Integer.parseInt(jtNumeroMesa.getText());
        Integer capacidad = Integer.parseInt(jtCapacidadMesa.getText());
        Boolean estado = jrbEstadoMesa.isSelected();
        
       mesa = new Mesa(numeroMesa, true, capacidad);
       medata.agregarMesa(mesa);
           
       }catch(NumberFormatException ex){
     JOptionPane.showMessageDialog(this, "Debe ingresar algo ");
    }
     llenarTablaMesa();
    }//GEN-LAST:event_jbAgregarMesaActionPerformed

    private void jbActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbActualizarMouseClicked
       if("".equals(jtID.getText())){
          JOptionPane.showMessageDialog(this, "Seleccione una fila ");
             }else{
               productoActual.setNombreProducto(jtNombreBuscar.getText());
               productoActual.setPrecio(Double.parseDouble(jtPrecio.getText()));
               productoActual.setStock(Integer.parseInt(jtCantidad.getText()));
               productoActual.setEstado(jrbEstado.isSelected());
               prodata.modificarProducto(productoActual);
      } 
    }//GEN-LAST:event_jbActualizarMouseClicked

    private void jbEliminarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarMesaActionPerformed
        int filasSelec=jtTablaMesa.getSelectedRow();
        if(filasSelec != -1){
            int idM = (Integer)modelo.getValueAt(filasSelec, 0);
           medata.borrarMesa(idM);
//            indata.borrarInscripcionMateriaAlumno(alumnoSeleccionado.getIdAlumno(), idM);
            
        }else{
           JOptionPane.showMessageDialog(this, "Por favor seleccione un producto");
        }
      llenarTablaMesa();
                       
    }//GEN-LAST:event_jbEliminarMesaActionPerformed

    private void jbLimpiarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarMesaActionPerformed
       limpiarMesas();
       llenarTablaMesa();
    }//GEN-LAST:event_jbLimpiarMesaActionPerformed

    private void jbModificarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarMesaActionPerformed
         if("".equals(jtIdMesa.getText())){
          JOptionPane.showMessageDialog(this, "Seleccione una fila ");
             }else{
               mesa.setIdMesa(Integer.parseInt(jtIdMesa.getText()));
               mesa.setNumero(Integer.parseInt(jtNumeroMesa.getText()));
               mesa.setEstadoMesa(jrbEstadoMesa.isSelected());
               mesa.setCapacidad(Integer.parseInt(jtCapacidadMesa.getText()));
              medata.modificarMesa(mesa);
      } 
        llenarTablaMesa();
    }//GEN-LAST:event_jbModificarMesaActionPerformed

    private void jbBuscarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarMesaActionPerformed
        try{
              Integer id = Integer.parseInt(jtIdMesa.getText());
              mesa = medata.buscarMesa(id);
            
            if(mesa !=null){
             
              jtIdMesa.setText(""+mesa.getIdMesa());
              jtNumeroMesa.setText(""+mesa.getNumero());
              jrbEstadoMesa.setText(""+mesa.isEstadoMesa());
              jtCapacidadMesa.setText(""+mesa.getCapacidad());
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Debe ingresar ");
        }
        llenarTablaMesa();
    }//GEN-LAST:event_jbBuscarMesaActionPerformed

    private void jbAgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarPedidoActionPerformed
        try{
//            pedido=(Pedido) jcbIdMesaPed.getSelectedItem();
//           Integer numeroMesa = Integer.parseInt(""+pedido.getIdMesa());
//            JOptionPane.showMessageDialog(this, numeroMesa);
        Integer numeroMesa = Integer.parseInt(jtIdMesaPedido.getText());
        String mesero = jtNombreMesero.getText();
        Double importe = Double.parseDouble(jtImporte.getText());
        Boolean cobro = jrbCobro.isSelected();
        
        pedido = new Pedido(numeroMesa, mesero,importe, cobro);
        pedata.agregarPedido(pedido);
       
           
       }catch(NumberFormatException ex){
     JOptionPane.showMessageDialog(this, "Debe ingresar algo ");
    }
     llenarTablaPedido();
                  
    }//GEN-LAST:event_jbAgregarPedidoActionPerformed

    private void jbEliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarPedidoActionPerformed
           int filasSelec=jtTablaPedidos.getSelectedRow();
        if(filasSelec != -1){
            int idM = (Integer)modelo.getValueAt(filasSelec, 0);
            pedata.borrarPedido(idM);
//            indata.borrarInscripcionMateriaAlumno(alumnoSeleccionado.getIdAlumno(), idM);
            
        }else{
           JOptionPane.showMessageDialog(this, "Por favor seleccione un Pedido");
        }
      llenarTablaPedido();  
    }//GEN-LAST:event_jbEliminarPedidoActionPerformed

    private void jcbPedidoVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPedidoVenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPedidoVenActionPerformed

    private void jPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorAdded
     
    }//GEN-LAST:event_jPanel2AncestorAdded

    private void jbEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEjecutarActionPerformed
          subtotal();
    }//GEN-LAST:event_jbEjecutarActionPerformed

    private void jbTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTotalActionPerformed
        total();
    }//GEN-LAST:event_jbTotalActionPerformed


    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableProducto;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbAgregarMesa;
    private javax.swing.JButton jbAgregarP;
    private javax.swing.JButton jbAgregarPedido;
    private javax.swing.JButton jbBuscarMesa;
    private javax.swing.JButton jbConsultarP;
    private javax.swing.JButton jbEjecutar;
    private javax.swing.JButton jbEliminarMesa;
    private javax.swing.JButton jbEliminarP;
    private javax.swing.JButton jbEliminarPedido;
    private javax.swing.JButton jbLimpiarMesa;
    private javax.swing.JButton jbLimpiarP;
    private javax.swing.JButton jbModificarMesa;
    private javax.swing.JButton jbModificarP;
    private javax.swing.JButton jbPedidoProducto;
    private javax.swing.JButton jbTotal;
    private javax.swing.JButton jbotonMesas;
    private javax.swing.JButton jbotonPedido;
    private javax.swing.JButton jbotonProducto;
    private javax.swing.JComboBox jcbIdMesaPed;
    private javax.swing.JComboBox<Pedido> jcbPedidoVen;
    private javax.swing.JComboBox<Producto> jcbProductosVen;
    private javax.swing.JLabel jlSubtotal;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JRadioButton jrbCobro;
    private javax.swing.JRadioButton jrbEstado;
    private javax.swing.JRadioButton jrbEstadoMesa;
    private javax.swing.JTextField jtCantidad;
    private javax.swing.JTextField jtCantidadVent;
    private javax.swing.JTextField jtCapacidadMesa;
    private javax.swing.JTextField jtID;
    private javax.swing.JTextField jtIdMesa;
    private javax.swing.JTextField jtIdMesaPedido;
    private javax.swing.JTextField jtIdPedido;
    private javax.swing.JTextField jtIdVent;
    private javax.swing.JTextField jtImporte;
    private javax.swing.JTextField jtNombreBuscar;
    private javax.swing.JTextField jtNombreMesero;
    private javax.swing.JTextField jtNumeroMesa;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTable jtTablaMesa;
    private javax.swing.JTable jtTablaPedidos;
    // End of variables declaration//GEN-END:variables

private void armarCabecera(){
    ArrayList<Object>titulo = new ArrayList();
 titulo.add("ID");
 titulo.add("Nombre");
 titulo.add("Precio");
 titulo.add("Cantidad");
 titulo.add("Estado");
 for(Object tit:titulo){
 modelo.addColumn(tit);
 }
 jTableProducto.setModel(modelo);
 
  }

private void armarCabeceraMesas(){
    ArrayList<Object>titulo = new ArrayList();
 titulo.add("ID");
 titulo.add("Numero");
 titulo.add("Capacidad");
 titulo.add("Estado");
 for(Object tit:titulo){
 modelo.addColumn(tit);
 }
 jtTablaMesa.setModel(modelo);
}

private void armarCabeceraPedidos(){
    ArrayList<Object>titulo = new ArrayList();
 titulo.add("ID");
 titulo.add("ID Mesa");
 titulo.add("Nombre Mesero");
 titulo.add("Fecha");
 titulo.add("Importe");
 titulo.add("Cobro");
 for(Object tit:titulo){
 modelo.addColumn(tit);
 }
 jtTablaPedidos.setModel(modelo);
}

private void llenarTablaProducto(){
    
           borrarFilasProducto();
            for(Producto p:prodata.listarProducto()){
                modelo.addRow(new Object[]{p.getIdProducto(),p.getNombreProducto(),p.getPrecio(),p.getStock(),p.isEstado()});
            }
    }
private void llenarTablaMesa(){
    
            borrarFilasMesa();
            for(Mesa m:medata.listarMesa()){
                modelo.addRow(new Object[]{m.getIdMesa(),m.getNumero(),m.getCapacidad(),m.isEstadoMesa()});
            }
    }

 private void llenarTablaPedido(){
            borrarFilasPedido();
            for(Pedido p:pedata.listarPedido()){
                modelo.addRow(new Object[]{p.getIdPedido(),p.getIdMesa(),p.getNombreMesero(),p.getFechaHora(),p.getImporte(),p.isCobro()});
            }
    }

private void borrarFilasProducto(){
  int filas=jTableProducto.getRowCount()-1;
  for(;filas>=0;filas--){
  modelo.removeRow(filas);
  }
}

private void borrarFilasMesa(){
int filas=jtTablaMesa.getRowCount()-1;
  for(;filas>=0;filas--){
  modelo.removeRow(filas);
  }
}

private void borrarFilasPedido(){
int filas=jtTablaPedidos.getRowCount()-1;
  for(;filas>=0;filas--){
  modelo.removeRow(filas);
  }
}
       
private void limpiarProducto(){
        jtID.setText("");
        jtNombreBuscar.setText("");
        jtPrecio.setText("");
        jtCantidad.setText("");
        jrbEstado.setSelected(true);
        
}

private void limpiarMesas(){
 jtID.setText("");
        jtIdMesa.setText("");
        jtNumeroMesa.setText("");
        jtCapacidadMesa.setText("");
       jrbEstadoMesa.setSelected(true);
        
}

private void limpiarPedido(){
        jtIdPedido.setText("");
        jtIdMesa.setText("");
        jtNombreMesero.setText("");
        jtImporte.setText("");
        jrbCobro.setSelected(true);
}

public void llenarComboMesero(){
//Guarda en la base
//    for(Pedido p : pedro.listarPedidoporMesero(nombre)){ //LISTAR ALUMNOS
////       jcbIdMesaVenta.addItem(m);
//    }
}

public void llenarComboPedido(){
    for(Pedido p : pedata.listarPedido()){ 
       jcbPedidoVen.addItem(p);
    }
} 

public void llenarComboProducto(){
    for(Producto p : prodata.listarProducto()){ 
       jcbProductosVen.addItem(p);
    }
} 

public void llenarComboPED(){
//Guarda en la base
    for(Mesa m:medata.listarMesa()){ //LISTAR ALUMNOS
       jcbIdMesaPed.addItem(m);
    }
}
 
private void subtotal(){
   
  pro=(Producto) jcbProductosVen.getSelectedItem();
  cantidad = Integer.parseInt(jtCantidadVent.getText());
  
   
    System.out.println("Subtotal "+pro.getPrecio() * cantidad);
    jlSubtotal.setText(pro.getPrecio() * cantidad+"");
  
   
      
    
//   public double calcularSubtotal() {
//        double subtotal = 0;
//        for (Producto producto : this.productos) {
//            subtotal += cantidad * pro.getPrecio();
//        }
//        return subtotal;
//     }
}
private void total(){
 double total =0;
 
 
  pro=(Producto) jcbProductosVen.getSelectedItem();
  cantidad = Integer.parseInt(jtCantidadVent.getText());
    total=+pro.getPrecio()*cantidad;
   
    
       System.out.println(total);
   
}

    
  
}

